# Generated by Django 5.0.2 on 2024-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='emprunte',
            field=models.BooleanField(default=False),
        ),
    ]
